exclude:
  - 'assets/src/styles/mixins/_mixins.scss'
  - 'assets/src/styles/libs/_pygments-manni.scss'

linters:
  ColorVariable:
    enabled: false
  ImportantRule:
    enabled: false
  LeadingZero:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  UnnecessaryMantissa:
    enabled: false
  UrlFormat:
    enabled: false
